version: '1.0'
services:
  mysql:
      container_name: wordpress_db
      environment:
          - MYSQL_ROOT_PASSWORD=pass
          - MYSQL_DATABASE=wordpressdb
          - MYSQL_USER=wordpress
          - MYSQL_PASSWORD=wordpress
      expose:
          - 3306
          - 33060
      volumes:
          - './data:/var/lib/mysql'
      image: mysql
  wordpress:
      container_name: wordpress-website
      environment:
          - WORDPRESS_DB_HOST=wordpress_db
          - WORDPRESS_DB_USER=wordpress
          - WORDPRESS_DB_PASSWORD=wordpress
          - WORDPRESS_DB_NAME=wordpressdb
      volumes:
          - './wp-data:/var/www/html'
      ports:
          - '5000:80'
      image: wordpress